### PR TITLE
Add support for 1-dimensional collections

### PR DESCRIPTION
**Pull request by gitblit**
This adds support for things like `List`, `Set`, and `TreeSet`.  The implementation covers Controllers and direct ParameterValue access from `RouteHandler`.  To compliment this feature, the `Request` will now recognize and assemble indexed-parameters.

### CODE REVIEW

**Comment by decebals** [comment]
:+1: 
Maybe a little update of documentation (pippo-site) help more to understand this feature.

**Comment by gitblit** [comment]
Definitely.  I will get that done - not today, though.

There are two halves to this feature

1. collections support
2. indexed parameter array support

Item 2 depends on 1 - but it is not the only way to use collections support.  If you supply multiple query parameters of the same name to a URL, that will result in a list of values which can take advantage of the collections too.  I'm not sure if you can simulate that with a form submit.  I think the last form input value of the same name will be used.  PHP and Django support item 2.  Maybe others too.

On a related front, #35, I've also been meaning to give [ajax-form](http://ajax-form.raynicholus.com/components/ajax-form/) a try.  Looks to be quite useful for declarative but modern forms.

**Comment by gitblit** [comment]
This will need some additional work if we want to support Collections in Body types.  This PR is mainly for parameter types.

In #130 I demo'd POSTing a JSON array as the BODY.  That works because the list component type is a string.  Our body parsing API does not support arrays of complex type (i.e List<MyType>).  It could, though.

**Comment by decebals** [comment]
Also I think that we have a bug.
For example #119 doesn't work.

```java
GET("/index", new RouteHandler() {

	@Override
	public void handle(RouteContext routeContext) {
		List<Integer> list = routeContext.getRequest().getParameter("list").toList(Integer.class);
		System.out.println("list = " + list);
	}

});

GET("/test", new RouteHandler() {

	@Override
	public void handle(RouteContext routeContext) {
		Map<String, Object> parameters = new HashMap<>();
		parameters.put("list", Arrays.asList(1, 2, 3));
		String uri = routeContext.uriFor("/index", parameters);
		System.out.println("uri = " + uri);
		routeContext.redirect(uri);
	}

});
```

Maybe I will create a quickstart for this.

**Comment by gitblit** [comment]
That can probably be supported.  It is a convenient, albeit nonstandard? format.

**Comment by decebals** [comment]
I don't care too much if the url query is standard or not for multi values parameter. The problem is that now the above snippet doesn't work.

> I think the proper way to specify a multi-valued parameter is to specify multiple key-value pairs.
e.g. /test?tags=tablet&tags=monitor&tags=laptop

I am ok with this approach, it is more standard.

Now, I see that I cannot upload the quickstart zip file so I will copy/paste the important part:

```java
GET("/index", new RouteHandler() {

	@Override
	public void handle(RouteContext routeContext) {
		List<Integer> list = routeContext.getRequest().getParameter("list").toList(Integer.class);
		System.out.println("list = " + list);
		routeContext.text().send(list);
	}

});

GET("/test", new RouteHandler() {

	@Override
	public void handle(RouteContext routeContext) {
		Map<String, Object> parameters = new HashMap<>();
		parameters.put("list", Arrays.asList(1, 2, 3));
		String uri = routeContext.uriFor("/index", parameters);
		System.out.println("uri = " + uri);
		routeContext.redirect(uri);
	}

});
``` 

In conclusion, for me the above issue is not important, we can leave it. It's a complex problem (for example I can put any object as parameter value) and I do not know if it's worth bother with it.

**Comment by gitblit** [comment]
See #131.

**Pull request merged**
