### PR TITLE
Add QueuedThreadPool to Jetty server

### PR DESCRIPTION
**Pull request by gustavogalvan**

### CODE REVIEW

**Comment by decebals** [comment]
I prefer the approach from #149, #151. In few words:
- create a `JettySettings` (similar with [UndertowSettings](https://github.com/decebals/pippo/blob/master/pippo-undertow/src/main/java/ro/pippo/undertow/UndertowSettings.java)) and put your settings in that file.
- change `JettyServer` to take into account the `JettySettings` class

I prefer each server with a custom settings `POJO` with some constants (properties names) and common settings in WebServerSettings.

What you say, make sense?

**Comment by gustavogalvan** [comment]
definitely your approach is better.

**Comment by decebals** [comment]
You come with another pull request or you want to create an issue?

**Comment by gustavogalvan** [comment]
I'll try again with a new pull request, with your approach.

**Pull request closed without merging**
