### PR TITLE
Filter implementation

### PR DESCRIPTION
**Pull request by danjee**
Add a Tomcat runtime

### CODE REVIEW

**Comment by gitblit** [comment]
Looks good.  Any particular reason for Tomcat 7 instead of Tomcat 8?

**Comment by danjee** [comment]
I had a talk with Decebal and decided not to use the PippoFilter with EmptyServlet but instead to use the PippoServlet directly without PippoFilter. 
I will rework and make another pull request.
Also I will put tomcat 8 dependency. I haven't used Tomcat 8 so far, that was the reason.

**Comment by decebals** [comment]
@gitblit What version you prefer between PippoFilter + EmptyServlet (I think that tomcat doesn't call the filter chain if you don't have a servlet on that context) vs PippoServlet?

**Comment by gitblit** [comment]
I think the `PippoServlet` approach in #141 is cleaner - since this is an embedded `WebServer` it doesn't really need to use a `ServletFilter`.  Thinking about it some more, maybe all the `WebServer` implementations should take a `PippoServlet` instead of a `PippoFilter`.

**Comment by danjee** [comment]
Maybe some rework is needed in `AbstractWebServer` by declaring some abstract methods so all implementations will follow a single pattern.
Also I think there is need for adding custom filters from client application for all implementations.

**Comment by decebals** [comment]
> Thinking about it some more, maybe all the `WebServer` implementations should take a `PippoServlet` instead of a `PippoFilter`.

Make sense.

**Pull request merged**
