### PR TITLE
Added more settings to Undertow

### PR DESCRIPTION
**Pull request by gustavogalvan**

### CODE REVIEW

**Comment by decebals** [comment]
For me it is too complicated with so many options. My idea is to supply only few options (I think the five existing options are sufficient) and if someone wants more she must override `Undetow.createServer(HttpHandler contextHandler)` and create a custom `Undertow` server.

**Comment by gustavogalvan** [comment]
ok

**Comment by decebals** [comment]
Thank you for your understanding.

**Comment by gustavogalvan** [comment]
you're welcome.

I thought you was going to like it because with this scheme you do not have to worry about all options, nor need a method for each. Only declared options were applied, otherwise the server takes its default settings.

**Comment by danjee** [comment]
I think it will be a pain keeping all this settings up to date with future Undertow releases. Also there are other servers that Pippo supports(Jetty, Tomcat, Tjws) and maybe other runtimes will be added in the future. If you have a complicated scheme for each you cannot keep the pace with the modifications.

**Comment by gustavogalvan** [comment]
That's is a big true. If you like we can continue this debate in the issue #166 (where I'm posting a comment), or create a thread in google forum.

**Pull request closed without merging**
