### PR TITLE
Move Initializers from PippoFilter to Application

### PR DESCRIPTION
**Pull request by gitblit**
Method names may need tweaking.

### CODE REVIEW

**Comment by decebals** [comment]
It's ok. For method names I propose this schema:

```java
final void init() { ... };

final void destroy() { ... };

protected void onInit() { ... }

protected void onDestroy() { ... }
```

With this visibility schema we don't pollute the Application's API. My two cents.

**Comment by gitblit** [comment]
`onInit()` and `onDestroy()` work for me.

The visibility decrease will hurt me for the short-run as I am not using `PippoFilter`.  I'm not sure I can re-align on `PippoFilter`.  Maybe.  I'll make the adjustments for the `on` methods but for now can we leave `init()` and `destroy()` public?

**Comment by gitblit** [comment]
Refactor pushed.

**Comment by decebals** [comment]
> The visibility decrease will hurt me for the short-run as I am not using PippoFilter.

You are not using PippoFilter? How?

**Pull request merged**
