### PR TITLE
Update Hazelcast unit test

### PR DESCRIPTION
**Pull request by barrantesgerman**
I don't have problems on master, but I found in [hazelcast documentation](http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#how-do-i-test-my-hazelcast-cluster) some tips, and it could solve the problem with the gzip pr.

I also uploaded the version to hazelcast to 3.7.4 (last stable)

### CODE REVIEW

**Comment by decebals** [comment]
@barrantesgerman Thanks! This PR resolves the problem. Now I see another problem, a build fail in TravisCI (https://travis-ci.org/decebals/pippo). I think that it's something related to memcache.

**Comment by barrantesgerman** [comment]
@decebals I'll check it

**Comment by decebals** [comment]
@barrantesgerman When I built the SNAPSHOT on my machine everything was OK. I don't know why this error appears on Travis CI.

**Comment by barrantesgerman** [comment]
@decebals It's because memcached unit tests (also redis and mongodb) download an executable to run memcached locally and run the test.

Travis is specifically trying to download [http://mirror.nclarkdev.com/memcached//1.4.22_1/memcached-dist-1.4.22_1-linux.tar.gz](http://mirror.nclarkdev.com/memcached//1.4.22_1/memcached-dist-1.4.22_1-linux.tar.gz)

On my machine I get:
```
403 Forbidden
You don't have permission to access /memcached//1.4.22_1/memcached-dist-1.4.22_1-linux.tar.gz on this server.
```
I'm using a dependency to embedded memcached on unit test
```xml
<dependency>
    <groupId>de.flapdoodle.embed</groupId>
    <artifactId>de.flapdoodle.embed.memcached</artifactId>
    <version>1.06.4</version>
    <scope>test</scope>
</dependency>
```
This dependency download the executable according to the operating system, probably the server where the linux executable is, it's having problems

**Comment by barrantesgerman** [comment]
I'm going to look for a solution or at least a similar dependency to do the test

**Comment by barrantesgerman** [comment]
@decebals I can not find a dependency that does the same, but I propose 3 possible solutions for you to choose:

1. Use [Travis](https://docs.travis-ci.com/user/database-setup/#Memcached) as memcached provider
  * Pro: Work well with Travis, I did the [test](https://travis-ci.org/barrantesgerman/pippo)
  * Con: If you run the tests locally, you need to install memcached first 
2. Use a external memcache provider as [memcachier.com](https://www.memcachier.com) (its free, with limitations)
  * Pro: Works locally and on Travis without installing anything
  * Con: It requires user name and password, so it would be visible in application.properties
3. Wait, I put a [issue](https://github.com/flapdoodle-oss/de.flapdoodle.embed.memcached/issues/11) on github (I do not think it's the best option, but it's still an option)
  * Pro: Works locally and on Travis without installing anything (When the server was up)
  * Con: I do not know how much time this could take

In my personal opinion, I like the first option more

**Pull request merged**
