### PR TITLE
add route name as first criterion in urlFor

### PR DESCRIPTION
**Pull request by decebals**
I try to implements the idea from the comment https://github.com/decebals/pippo/pull/99#issuecomment-77233748

In few words I can add a route (in an hypothetical blog application) with:
```java
GET("/blogs/{year}/{month}/{day}/{title}", (routeContext) -> { routeContext.render("myTemplate)});
```

It's hard to create the reverse routing using the `uriPattern`:
```java
Map<String, Object> parameters = ...
routeContext.uriFor("/blogs/{year}/{month}/{day}/{title}", parameters);
```

Now you can add a `name` for a route and to use this name when you build the URL(reverse routing) to that route:
```java
GET("/blogs/{year}/{month}/{day}/{title}", (routeContext) -> { routeContext.render("myTemplate)}).named("blog");
```

The new cod becomes:
```java
Map<String, Object> parameters = ...
routeContext.uriFor("blog", parameters);
```

Advantages:
- it is often more descriptive than hard-coding the `uriPattern`
- it allows you to change `uriPattern` in one go, without having to remember to change URLs all over the place.

I will try to add the same approach for `redirect`.

What you say?

### CODE REVIEW

**Comment by gitblit** [comment]
I'm a big fan of the idea but It looks like I can only lookup by *name* once I have named a route.

**Comment by decebals** [comment]
Yes, it's a bug. Thanks. I never thought that someone that someone wants to search by `uriPattern` when he has the shortcut with `name` :smile:

**Comment by decebals** [comment]
I fixed it.

**Comment by gitblit** [comment]
Well I doubt I would want to lookup by uri if I named it but if we advertise lookup by X or Y then it should work for both cases.

Looks good to me.  Merge it!

**Pull request merged**
